### PR TITLE
Fix electron webview keyinput event not propagaded

### LINKED ISSUE #2125: Keyboard shortcuts to cycle through service tabs doesn't work
### Steps to reproduce

1. Update to 0.6.4
2. Have multiple service tabs running (I have Whatsapp, Skype, Mattermost, Messenger)
3. Focus in one of them while using it.
4. Hit CTRL+TAB or CTRL+PGUP/PGDN to cycle through them

### Expected behavior

Tab switches to the next one on the right like it did in previous versions.

### Actual behavior

Nothing happens.
If you mouse click on the Service tab header itself (eg the "Whatsapp" icon and text) and then hit CTRL+TAB or CTRL+PGUP it works just once. You then need to mouse click on the current Service tab header again before CRTL+TAB or CTRL+PGUP to switch to the next one.

Looks like this functionality was introduced in #75. I've been using it for many versions.

### ENVIRONMENT

Rambox 0.6.4
Electron 3.1.4
win32 x64 10.0.17134

### LINKED ISSUE #2127: CTRL+TAB no longer working in 0.6.4
In 0.6.3 I was able to make use of the next / prev tab shortcuts to switch between the services. In 0.6.4 that feature doesn't seem to work anymore.

1. Upgrade from 0.6.4
2. Have multiple services (tabs) enabled
3. Use CTRL+TAB (WIN & MAC) or CTRL+SHIFT+TAB to navigate tabs

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> darwin x64 17.7.0

### LINKED ISSUE #2136: Change between Enabled services using "Ctrl"+"pg dn" is not longer working
I can't change from one Enabled service to an other using "Ctrl"+"pg dn" or "Ctrl"+"pg up". In the last version it was possible. Also "Ctrl"+"Tap" only works if I'm on the tab name. Thanks.
	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17134

### LINKED ISSUE #2159: Keyboard shortcuts for switching tabs failing
### Steps to reproduce

1. Try using CTRL-TAB or CTRL-SHIFT-TAB and it fails

### Expected behavior
Switch tabs

### Actual behavior
Nothing happens

### ENVIRONMENT
Version: 0.6.4
Platform: win32 (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0

### LINKED ISSUE #2161: Rambox shortcuts not working
My Ctrl+1,2,3,4,tab etc buttons don't work somehow

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17134

### LINKED ISSUE #2164: Rambox Keyboard Shortcuts no longer working from within services
Rambox specific shortcuts no longer appear to be working when in a service's tab.

Reproduction steps:
Open rambox, go into a service (discord, messenger, slack whatever) attempt to switch to another service using CRTL + Number of the service.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17763

### PR DESCRIPTION
**Pull request by maxerbox**
Since chromium's architecture has been reworked, events are not propaged globally anymore. Rambox was using this hack to handle CTRL+TAB, but with the new electron version, it's not working anymore.
A workaround is to handle the events fired by webview.

Here is a fix.

Fixes #2125 
Fixes #2127
Fixes #2136
Fixes #2161 
Fixes #2159 
Fixes #2164

### CODE REVIEW

**Comment by adavidzh** [comment]
Any idea if this resolves the same issue on Mac OS X?

**Comment by maxerbox** [comment]
Fixed pageup-pagedown-zoomin-zoomout issue

**Comment by avielc** [comment]
@maxerbox  - When will that commit be available to download as an update to Rambox?

**Comment by maxerbox** [comment]
I hope soonest as possible

**Comment by ShadowSonic** [comment]
Pls review, i miss STRG + TAB here

**Comment by maxerbox** [comment]
You are welcome to test it!

**Comment by avielc** [comment]
Waiting for it to be deployed out so I can see it live on my Rambox on Windows

File: app/ux/WebView.js [hunk 1]
```diff
@@ -454,6 +454,29 @@ Ext.define('Rambox.ux.WebView',{
 
 			webview.executeJavaScript(js_inject);
 		});
+		webview.getWebContents().on('before-input-event', (event, input) => {
+			if (input.type !== 'keyDown') { // event used by default
+				return;
+			}
+			// because keyCode property is not passed
+			const keycode = require('keycodes')
```
Comment (saenzramiro) [inline app/ux/WebView.js]: I think this can be moved outside the event, to prevent calling the require every time the user press a key.

**Comment by avielc** [comment]
any updates on when it'll be deployed into  v0.65? 
Thanks
also, if it'll take a while, can anyone give me a brief explanation on how to create \ change the files on the local 0/64 installed ? Using windows client

Thanks again :)

**Comment by BalintFarkas** [comment]
Can't wait for this to be released :)

**Comment by maxerbox** [comment]
We have to look at another thing before 0.6.5, it seems there is an issue with whatsapp that make a regression

**Comment by BalintFarkas** [comment]
Ahh, the hotkeys work again in 0.6.6. Didn't know how much I relied on them until they were gone. :) Thanks a lot @maxerbox !

**Comment by adavidzh** [comment]
Thanks for getting something working again: I confirm that on MacOS X `⌃+PgUp` and `⌃+PgDn` work. Unfortunately it seems that `⌘+1`, ..., `⌘+9` do not work as they used to.

`⌘+N` is used in all browsers to go to the `N`th tab (or the last one for `N`=9). Another feature of most browsers is for `⌃+{` and `⌃+}` to move to the previous and next tab respectively. This also does not work. Ditto for `⌃+[` and `⌃+]`.

How can I contribute this?

**Comment by BalintFarkas** [comment]
For the record, all hotkeys (Ctrl+Tab, Ctrl+Shift+Tab, Ctrl+PgUp, Ctrl+PgDn, Ctrl+number) work on Windows.

**Comment by maxerbox** [comment]
Same, everything fine on Debian

**Comment by maxerbox** [comment]
@adavidzh You should open a new issue
